name: simple_barcode_scanner
description: simple_barcode_scanner that let you scan barcode and qr code in mobile, web and windows.
version: 260.213.0

platforms:
  android:
  ios:
  web:
  windows:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.31
  path: ^1.9.1
  permission_handler: ^12.0.1
  web: ^1.1.1
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

flutter:
  assets:
    - packages/simple_barcode_scanner/assets/barcode.html
    - packages/simple_barcode_scanner/assets/html5-qrcode.min.js
  plugin:
    platforms:
      android:
        package: com.amolg.flutterbarcodescanner
        pluginClass: FlutterBarcodeScannerPlugin
      ios:
        pluginClass: SwiftFlutterBarcodeScannerPlugin
